gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c cd_audio.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c chase.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c cl_demo.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c cl_input.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c cl_main.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c cl_parse.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c cl_tent.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c cmd.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c common.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c console.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c crc.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c cvar.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c d_edge.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c d_fill.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c d_init.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c d_modech.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c d_part.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c d_polyse.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c d_scan.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c d_sky.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c d_sprite.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c d_surf.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c d_vars.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c d_zpoint.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c dos_v2.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c draw.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c host.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c host_cmd.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c in_dos.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c keys.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c mathlib.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c menu.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c model.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c mplib.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c net_loop.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c net_main.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c net_none.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c net_vcr.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c nonintel.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c pr_cmds.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c pr_edict.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c pr_exec.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c r_aclip.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c r_alias.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c r_bsp.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c r_draw.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c r_edge.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c r_efrag.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c r_light.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c r_main.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c r_misc.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c r_part.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c r_sky.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c r_sprite.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c r_surf.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c r_vars.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c sbar.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c screen.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c snd_dma.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c snd_dos.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c snd_gus.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c snd_mem.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c snd_mix.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c sv_main.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c sv_move.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c sv_phys.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c sv_user.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c sys_dos.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c vid_dos.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c vid_ext.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c vid_vga.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c view.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c vregset.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c wad.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c world.c
gcc -std=gnu90 -trigraphs -fcommon -fexpensive-optimizations -O3 -c zone.c
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c d_copy.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c d_draw.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c d_draw16.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c d_parta.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c d_polysa.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c d_scana.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c d_spr8.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c d_varsa.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c dosasm.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c math.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c r_aclipa.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c r_aliasa.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c r_drawa.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c r_edgea.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c r_varsa.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c snd_mixa.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c surf16.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c surf8.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c sys_dosa.s
gcc -x assembler-with-cpp -fcommon -fexpensive-optimizations -O3 -c worlda.s
gcc -lm -v -s *.o -o QUAKE_N.EXE
